version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t chatops/perceptron .
      - docker tag chatops/perceptron:latest 511364101674.dkr.ecr.us-east-1.amazonaws.com/chatops/perceptron:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 511364101674.dkr.ecr.us-east-1.amazonaws.com/chatops/perceptron:latest
      - printf '[{"name":"perceptron","imageUri":"%s"}]' 511364101674.dkr.ecr.us-east-1.amazonaws.com/chatops/perceptron:latest > imagedefinitions.json
  artifacts:
    files: imagedefinitions.json
  